### ISSUE TITLE
Sobre Divulgação de vagas de emprego

### ISSUE THREAD

**Issue by vtrbtf** [telegram-it-groups/code-of-conduct#16]
Ola.

Fiquei em duvida em relação da seção [#4.2](https://github.com/telegram-it-groups/code-of-conduct#42-divulgar-vagas-de-emprego). 
Pelo texto, parece que fica aberto para o uso de head hunters, o que eu particularmente acho ruim. IMHO eu acho que a divulgação de vagas poderia se limitar a vagas casuais que os participantes tenham conhecimento ( dentro da sua empresa, por exemplo ), e onde o material do divulgador não se limite apenas a divulgação da vaga em si. 

Ja vi algumas pessoas ( que pareciam ser head hunters ) divulgando constantemente vagas em grupos e acho que isso cria noise e indireção.

**Comment by igorsantos07** [comment]
Eu particularmente nao vejo problema com vagas externas sendo anunciadas - pra isso tem a cláusula de consultar os admins antes. Se os moderadores considerarem que já houve demais, ou que não combina com o estilo do grupo, eles vetam :)

**Comment by ghost** [comment]
Como o Igor disse, basta conversar com os admins antes, tudo se resolve numa boa conversa.
