### ISSUE TITLE
Há necessidade de uma licença CC-BY?

### ISSUE THREAD

**Issue by igorsantos07** [telegram-it-groups/code-of-conduct#22]
Bom, isso é um código de conduta... para uso aberto... Precisamos mesmo explicitamente atribuir a criação dele ao dono? Não faz muito sentido pra mim... rs
Ainda mais se considerar que o criador já é citado no corpo do código de conduta - sem mencionar os contribuidores.

**Comment by ghost** [comment]
Adicione a lista de contribuidores via PR que eu faço merge.

**Comment by ghost** [comment]
Quanto a licença estou viajando, mas vejo que sua colocação faz sentido, qual sua sugestão de licença para o CoC?

**Comment by igorsantos07** [comment]
Eu simplesmente tiraria a cláusula BY, que obriga referenciar o autor
original :)

Mais tarde envio um PR citando a lista de contribuidores do Github no
readme.

**Comment by ghost** [comment]
Ok!
