### ISSUE TITLE
Sugestão de melhoria

### ISSUE THREAD

**Issue by rodrigorootrj** [telegram-it-groups/code-of-conduct#57]
No tópico 4,1, tem uma ambiguidade., pois no primeiro subtopico diz para não divulgar vagas sem consultar os asmins, depois diz para não divulgar vagas que não estão ligadas ao grupo. O correto seria: **Caso queira consultar os admins, consultenos apenas sobre vagas relacionadas TI.**

Segue abaixo o sópico completo:
4.2 Divulgar vagas de emprego
Não divulgue vagas de emprego sem consultar os admins (em pvt);
Não divulgue vagas de emprego que não estejam ligadas ao tema do grupo ou relacionadas com TI;
Se preferir, existem canais específicos para este tipo de atividade, procure na lista de canais.

**Comment by ghost** [comment]
Vou ajustar, obrigado.
