### ISSUE TITLE
Correções no tópico anti-harassment para assegurar imparcialidade 🙂

### ISSUE THREAD

**Issue by ivanaugustobd** [telegram-it-groups/code-of-conduct#59]
No 1° tópico, "Política anti-harassment", há um ponto mencionando que "piadas" de determinados tipos não serão aceitas:
> Piadas sexistas, machistas, misóginas ou discriminatórias, contra minorias, pessoas ou grupos não serão toleradas;
<hr>
Gostaria de pontuar algumas questões:<br><br>

> Piadas sexistas, machistas
- Desnecessário o uso do termo "machistas" após citar sexismo (pleonasmo).
> misóginas
- Piadas misândricas estão liberadas?
> contra minorias
- Quais os critérios para um grupo ser classificado como "minoria"? Piadas contra quem não atender tais critérios (maiorias?) estão liberadas?
<hr>

Sugestão para resolver as questões acima, de forma a abordar todas as pessoas/grupos **de forma imparcial**:

> Piadas sexistas, misóginas/misândricas, discriminatórias, contra qualquer pessoa ou grupo não serão toleradas.
<hr>

Me disponho a fazer a PR se precisar, só queria discutir a questão primeiro para ver se deixei passar algo 😉

**Comment by geekcom** [comment]
1. O uso da palavra "misandria" não faz sentido nas nossas regras de conduta dentro do contexto dos grupos de tecnologia onde a maioria é homem hétero, não existe preconceito entre os iguais.

2. O termo "machista" deve ser usado sim, milhares de mulheres são mortas todos os dias por seus companheiros que carregam esse conjunto de princípios que os leva a atitudes violentas que se enquadram em "machismo". Não usar o termo equivale a negar a existência desse fato.

3. Sobre as minorias nós sabemos historicamente quem são, não há necessidade de estender esse tópico.

**Comment by ivanaugustobd** [comment]
1 - fico feliz que no mundo paralelo em que você vive seja assim. No mundo real [o que está havendo de homens feministas e brancos sendo genuinamente racistas com outros brancos](https://twitter.com/search?q=vergonha%20de%20ser%20branco%20homem&src=typed_query) (a título de exemplo) não está escrito. Mas a discriminação pelo visto só importa se for contra determinados grupos né?

2 - a atitude em si já está contida no primeiro termo. Da forma atual está tão redundante quanto "subir pra cima", "descer pra baixo" e etc. Mas outra possibilidade para não precisar remover tal termo seria coibir ambos os tipos de sexismo explicitamente:
> Piadas machistas ou feministas, [..]

3 - na prática, "minoria" não passa de um termo usado para se referir à grupos que sejam de interesse político no momento. Não há porque ser seletivo quanto à que tipos de discriminação que não serão aceitas.

Em resumo: não há motivo válido para usar "dois pesos, duas medidas" como está hoje.

**Comment by ivanaugustobd** [comment]
É triste ver o ambiente tóxico que a comunidade de TI nacional está se tornando. Depois de eventos com taxa de gênero/cotas sexistas (sob o pretexto insanamente sofista, sentimentalista e hipócrita de estar promovendo igualdade), agora um "CoC" que inibe certos tipos de discurso de ódio e deixa outros em aberto? (na prática "legalizando" estes, já que a pessoa não estaria violando regra nenhuma) Realmente triste isso, especialmente tendo em vista que não era assim (lembram do "esse grupo não tem regras, _tenha bom senso_ se não quiser ser banido"?). 😪

Vou guardar com carinho as memórias da época que os grupos e eventos _eram_ **para todos** (e continuar apoiando os que ainda são, claro).

**Comment by geekcom** [comment]
Beleza, mas suas sugestões de alteração jamais passarão.

**Comment by ivanaugustobd** [comment]
Agora repitam comigo que nem um zumbi: "não existe preconceito entre os iguais"

![image](https://user-images.githubusercontent.com/4603111/102606556-a98a7f00-4105-11eb-85c1-943a38b366f2.png)

Fonte: https://twitter.com/wilcorrea/status/1268517484166086656

Não me admira a menção à machismo e misoginia ao mesmo tempo que fazem vista grossa à feminismo e misandria.
